framework:
    cache:
        prefix_seed: askona/askona-api

        app: cache.adapter.redis
        default_redis_provider: 'redis://redis:%env(REDIS_PORT_TARGET)%/0'

        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.query_cache_pool:
                adapter: cache.system
            doctrine.metadata_cache_pool:
                adapter: cache.system
