version: "3.9"

# Development environment override
services:
    php:
        build:
            target: app_php_dev
        volumes:
            - ./:/srv/app
            - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
            - ./var/log:/srv/app/var/log
            - /srv/app/vendor
        environment:
            # https://xdebug.org/docs/all_settings#mode
            XDEBUG_MODE: "${XDEBUG_MODE:-off}"
        extra_hosts:
            # Ensure that host.docker.internal is correctly defined on Linux
            - host.docker.internal:host-gateway

    redis:
        ports:
            - ${REDIS_PORT_PUBLIC:-6379}:${REDIS_PORT_TARGET:-6379}
